### ISSUE TITLE
Edit timers 

### ISSUE THREAD

**Issue by dan-l** [D-PLAN/Vibernate-2#13]
Be able to select and edit a particular timer from  week view and list view 

@napon @ameliayap @Paul-Kijtapart

**Comment by dan-l** [comment]
Selected timer is bundled and pass into created timer activity from weekview

**Comment by napon** [comment]
I remember we ran into this bug where the week view didn't update itself when a timer is edited. Has this been fixed?

**Comment by dan-l** [comment]
Yep. On the latest commit it is. Let me know if it isn't.
