### ISSUE TITLE
Icons are squished (Daniel)

### ISSUE THREAD

**Issue by liaesque** [D-PLAN/Vibernate-2#17]
In the Week View, the icons in the colour blocks are squished.

**Comment by dan-l** [comment]
@liaesque   whitespace trimmed icons please?

**Comment by napon** [comment]
Trimmed white space and replaced the icons in commit bc1fc72cbde696471738db17c29bd637ddd04c46

**Comment by dan-l** [comment]
So far looks good, will re-open if further changes are needed
