### ISSUE TITLE
Refine tutorial instructions

### ISSUE THREAD

**Issue by napon** [D-PLAN/Vibernate-2#20]

**Comment by napon** [comment]
done dbab746fd0803c02ff4a12feabc34dbb588cf5fe

**Comment by dan-l** [comment]
@napon  I think we are need instructions for edit and delete, what do you think?

**Comment by napon** [comment]
Added instruction for edit. I think delete is already clear enough with the trash icon

**Comment by dan-l** [comment]
Oops, i modified edit and delete gesture, they will now appear in the swipe layout

**Comment by napon** [comment]
done
