### ISSUE TITLE
Need custom image for the last tutorial screen

### ISSUE THREAD

**Issue by napon** [D-PLAN/Vibernate-2#21]
Lia pls

**Comment by napon** [comment]
Another idea is to have this screen be an "About us" page with our names and pictures?

**Comment by dan-l** [comment]
Can we combine both

**Comment by napon** [comment]
Are u suggesting a custom image as ur picture??

**Comment by dan-l** [comment]
^

**Comment by napon** [comment]
Gonna use custom image for the play store listing instead
