### ISSUE TITLE
Delete timer design decision on week view

### ISSUE THREAD

**Issue by dan-l** [D-PLAN/Vibernate-2#23]
How should we allow the user to delete a timer?  Is current trash icon OK? Or something else?

**Comment by dan-l** [comment]
Currently trying out swipe view, will get more opinion from others

**Comment by napon** [comment]
Log of what I did:
- Background is now dynamic based on timer's color
- Swipe is disabled when displaying the place holder timer view

https://github.com/daimajia/AndroidViewHover

Take a look at this library I think this works better for modifying/delete our timers

**Comment by dan-l** [comment]
Outstanding issue - Without swiping first tap is unresponsive (looks like edge wasn't updated from default   right edge if swipe is never invoked) 

EDIT fixed in 06d300bb2b8418d6b219caa8b939505e0e43071b
