### ISSUE TITLE
Refactor invalidateDisplayTimerInfo in timerweekview

### ISSUE THREAD

**Issue by dan-l** [D-PLAN/Vibernate-2#28]

**Comment by napon** [comment]
I noticed a bug with the toggle not turning gray

Steps to reproduce:
- create a timer
- toggle it off 
- create another timer
- click the second timer to view details
- click the first timer to view details

The toggle is not gray even though its off

**Comment by napon** [comment]
^ just fixed the issue described up there in commit 4b1670b1ec536123f88487f647e038e27241b955
