### ISSUE TITLE
Material design backward compatibility for older Android version

### ISSUE THREAD

**Issue by dan-l** [D-PLAN/Vibernate-2#3]
https://chris.banes.me/2014/10/17/appcompat-v21/

**Comment by napon** [comment]
How far back do you plan to make it compatible for?

**Comment by dan-l** [comment]
http://www.appbrain.com/stats/top-android-sdk-versions

min sdk  jellyBean ?

**Comment by napon** [comment]
Sure! Go ahead and change the minSDK let me know if it creates any problems!

**Comment by dan-l** [comment]
6e88116eaa90bc8257ef8c99a90519c20c35eee1

Did not see any problems with Lollipop emulator, can't say the same about the other version since we haven't yet implement backward compatibility so it won't run for other devices currently

**Comment by napon** [comment]
We need to change the current code to use stuff from the Support library as well. Otherwise, the app will go boom when we try to run it on jelly bean phones

**Comment by dan-l** [comment]
cca99dac54e03393e9f147f0b42a6976905d7c9a

No more boom for kitkaters and jellbeaners
