### ISSUE TITLE
When timer blocks are too small relative to other timers on weekview 

### ISSUE THREAD

**Issue by dan-l** [D-PLAN/Vibernate-2#31]
If block is smaller than icon, do not display them and notify user that they will see them in list view

**Comment by napon** [comment]
Warning dialog can be something like this: 
"The timer you are creating is too short compared to your other timers, and will not be rendered on the week view. You can switch to the list view to modify this timer instead"

**Comment by dan-l** [comment]
I have already implemented one on the placeholder instead :o  
Could you pull my branch 'daniel' and see if the changes for week view are suitable? @napon

**Comment by napon** [comment]
Looks great! I removed the period (.) at the end to be consistent with the tutorial text
