### ISSUE TITLE
Issue with time representation when creating a timer

### ISSUE THREAD

**Issue by napon** [D-PLAN/Vibernate-2#32]
![11288601_10153376119164874_350366044_o](https://cloud.githubusercontent.com/assets/5266819/7807568/806be9c2-0341-11e5-81ae-60edb1efa248.jpg)

**Comment by napon** [comment]
fixed in commit 13a44728c6176daa67bbc048755be9d362d1f03a

**Comment by dan-l** [comment]
Another issue is that the end time isn't 1 hour apart from start time, which it should

**Comment by napon** [comment]
FIX INCOMING

**Comment by napon** [comment]
fixed in b10ee7e1e134fa6ed3dc1f3448a2f4a88e9dabec
