### ISSUE TITLE
Invalidate TimerInfo not called?

### ISSUE THREAD

**Issue by napon** [D-PLAN/Vibernate-2#33]
When editing a timer's color, after pressing done, the color of the timerinfo window is not updated.

**Comment by dan-l** [comment]
color of timerinfo window? could u post a screenshot?

**Comment by napon** [comment]
![screenshot_2015-05-26-20-19-15](https://cloud.githubusercontent.com/assets/5266819/7828159/a53a2c66-03e4-11e5-9ea3-253eb5b5e731.png)

**Comment by napon** [comment]
![screenshot_2015-05-26-20-21-11](https://cloud.githubusercontent.com/assets/5266819/7828172/c66214da-03e4-11e5-8bb9-0e0b07cb97f6.png)

**Comment by dan-l** [comment]
CANNOT REPRODUCE @napon
