### ISSUE TITLE
Week view design

### ISSUE THREAD

**Issue by napon** [D-PLAN/Vibernate-2#5]

**Comment by dan-l** [comment]
@ameliayap

**Comment by dan-l** [comment]
Implemented with custom view 

TODOs 
use the right icons (vibrate and silent icons - black, white)
handle the timer on/off, delete buttons

**Comment by dan-l** [comment]
TODO Reopened to revisit how the timer's info are updated after editing

**Comment by napon** [comment]
https://github.com/daimajia/AndroidViewHover

Take a look at this library I think this works better for modifying/delete our timers
